

server:
  port: 20000
  servlet:
    context-path: /dataread
spring:
  application:
    name: "data-read"
  datasource:
    url: jdbc:mysql://localhost:3306/elm_2024?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone : "http://eureka10000:10000/eureka,http://eureka10001:10001/eureka"