resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        waitDurationInOpenState: 5s
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      circuitBreakerA:
        failureRateThreshold: 30
server:
  port: 8085
spring:
  application:
    name: gateway
#下面是关于Spring Cloud Gateway的配置
  cloud:
    gateway:
      routes:
        - id: business
          uri: lb://business
          predicates:
            - Path=/business/**
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/cart/**
        - id: food
          uri: lb://food
          predicates:
            - Path=/food/**
        - id: delivery-address
          uri: lb://delivery-address
          predicates:
            - Path=/deliveryaddress/**
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/orders/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: circuitBreakerA
#                fallbackUri: forward:/fallback/business
      globalcors:
#        配置全局 CORS 策略，[/**] 表示应用于所有路径的请求。
        corsConfigurations:
          '[/**]':
#            允许所有的域名进行跨域请求。
            allowedOrigins: "*"
#            指定允许的 HTTP 方法列表。
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
#            允许所有的请求头。
            allowedHeaders: "*"

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eureka10000:10000/eureka,http://eureka10001:10001/eureka"

